import { Job } from '@/types/job';

export const mockJobs: Job[] = [
    {
        id: '1',
        jobNumber: 'JOB-2025-0907-001',
        ticketReference: 'SRTK100',  // Links to ticket-2
        customer: 'Demo Corporation',
        site: 'London HQ',
        description: 'HVAC system malfunction - Air conditioning unit not cooling effectively in server room',
        engineer: 'John Smith',
        status: 'allocated',
        priority: 'High',
        category: 'HVAC',
        jobType: 'Repair',
        targetCompletionTime: 240,
        dateLogged: new Date('2024-01-15T09:00:00'),
        dateAccepted: new Date('2024-01-15T09:30:00'),
        dateOnSite: new Date('2024-01-15T10:15:00'),
        dateCompleted: null,
        tenant: 'FM4U Ltd',
        alerts: [],
        reason: null,
        contact: {
            name: 'Sarah Johnson',
            number: '+447123456789',
            email: 'sarah.johnson@democorp.com',
            relationship: 'Facilities Manager'
        },
        reporter: {
            name: 'Sarah Johnson',
            number: '+447123456789',
            email: 'sarah.johnson@democorp.com',
            relationship: 'Facilities Manager'
        },
        primaryJobTrade: 'HVAC',
        secondaryJobTrades: ['Electrical', 'General'],
        tags: ['HVAC', 'Emergency', 'Cooling', 'Server Room', 'Repair'],
        customAlerts: {
            acceptSLA: 30,
            onsiteSLA: 90,
            completedSLA: 240
        },
        project: 'HVAC Maintenance',
        customerOrderNumber: 'PO-2024-001',
        referenceNumber: 'REF-001',
        jobOwner: 'Facilities Department',
        jobRef1: 'HVAC-001',
        jobRef2: 'SR-001',
        requiresApproval: false,
        preferredAppointmentDate: new Date('2024-01-16T10:00:00'),
        startDate: new Date('2024-01-15T09:00:00'),
        endDate: null,
        lockVisitDateTime: false,
        deployToMobile: true,
        isRecurringJob: false,
        completionTimeFromEngineerOnsite: false
    },
    {
        id: '2',
        jobNumber: 'JOB-2025-0907-002',
        ticketReference: 'SRTK101',
        customer: 'Tech Solutions Ltd',
        site: 'Manchester Office',
        description: 'Leaky faucet in breakroom - Constant drip from the breakroom sink faucet',
        engineer: 'Sarah Johnson',
        status: 'attended',
        priority: 'Medium',
        category: 'Plumbing',
        jobType: 'Maintenance',
        targetCompletionTime: 120,
        dateLogged: new Date('2024-01-14T14:30:00'),
        dateAccepted: new Date('2024-01-14T15:00:00'),
        dateOnSite: null,
        dateCompleted: null,
        tenant: 'WorkFlowX',
        alerts: [{ type: 'WARNING', message: 'Approaching Attendance SLA' }],
        reason: null,
        contact: {
            name: 'Mike Davis',
            number: '+447234567890',
            email: 'mike.davis@techsolutions.com',
            relationship: 'Office Manager'
        },
        reporter: {
            name: 'Mike Davis',
            number: '+447234567890',
            email: 'mike.davis@techsolutions.com',
            relationship: 'Office Manager'
        },
        primaryJobTrade: 'Plumbing',
        secondaryJobTrades: ['General'],
        tags: ['Plumbing', 'Leak', 'Maintenance', 'Breakroom', 'Faucet'],
        customAlerts: {
            acceptSLA: 60,
            onsiteSLA: 180,
            completedSLA: 360
        },
        project: 'Office Maintenance',
        customerOrderNumber: 'PO-2024-002',
        referenceNumber: 'REF-002',
        jobOwner: 'Office Management',
        jobRef1: 'PLUMB-001',
        jobRef2: 'BR-001',
        requiresApproval: false,
        preferredAppointmentDate: new Date('2024-01-15T09:00:00'),
        startDate: new Date('2024-01-14T14:30:00'),
        endDate: null,
        lockVisitDateTime: false,
        deployToMobile: true,
        isRecurringJob: false,
        completionTimeFromEngineerOnsite: false
    },
    {
        id: '3',
        jobNumber: 'JOB-2025-0907-003',
        ticketReference: 'SRTK102',
        customer: 'Industrial Manufacturing',
        site: 'Birmingham Factory',
        description: 'Electrical outlet repair - Several power outlets in production area are not working',
        engineer: 'Mike Davis',
        status: 'completed',
        priority: 'High',
        category: 'Electrical',
        jobType: 'Repair',
        targetCompletionTime: 180,
        dateLogged: new Date('2024-01-13T10:00:00'),
        dateAccepted: new Date('2024-01-13T10:15:00'),
        dateOnSite: new Date('2024-01-13T11:00:00'),
        dateCompleted: new Date('2024-01-13T14:00:00'),
        tenant: 'Guardian Environmental',
        alerts: [],
        reason: null,
        contact: {
            name: 'Lisa Wilson',
            number: '+447345678901',
            email: 'lisa.wilson@indmanufacturing.com',
            relationship: 'Production Manager'
        },
        reporter: {
            name: 'Lisa Wilson',
            number: '+447345678901',
            email: 'lisa.wilson@indmanufacturing.com',
            relationship: 'Production Manager'
        },
        primaryJobTrade: 'Electrical',
        secondaryJobTrades: ['General'],
        tags: ['Electrical', 'Power', 'Repair', 'Production', 'Outlets'],
        customAlerts: {
            acceptSLA: 30,
            onsiteSLA: 90,
            completedSLA: 180
        },
        project: 'Electrical Maintenance',
        customerOrderNumber: 'PO-2024-003',
        referenceNumber: 'REF-003',
        jobOwner: 'Production Department',
        jobRef1: 'ELEC-001',
        jobRef2: 'PA-001',
        requiresApproval: false,
        preferredAppointmentDate: new Date('2024-01-13T10:00:00'),
        startDate: new Date('2024-01-13T10:00:00'),
        endDate: new Date('2024-01-13T14:00:00'),
        lockVisitDateTime: false,
        deployToMobile: true,
        isRecurringJob: false,
        completionTimeFromEngineerOnsite: false
    },
    {
        id: '4',
        jobNumber: 'JOB-2025-0907-004',
        ticketReference: 'SRTK103',
        customer: 'Demo Corporation',
        site: 'London HQ',
        description: 'Routine HVAC maintenance - Annual check-up and filter replacement for all HVAC units',
        engineer: 'John Smith',
        status: 'attended',
        priority: 'Low',
        category: 'HVAC',
        jobType: 'Maintenance',
        targetCompletionTime: 480,
        dateLogged: new Date('2024-01-16T08:00:00'),
        dateAccepted: null,
        dateOnSite: null,
        dateCompleted: null,
        tenant: 'FM4U Ltd',
        alerts: [{ type: 'OVERDUE', message: 'Attendance SLA Breached' }],
        reason: null,
        contact: {
            name: 'Sarah Johnson',
            number: '+447123456789',
            email: 'sarah.johnson@democorp.com',
            relationship: 'Facilities Manager'
        },
        reporter: {
            name: 'Sarah Johnson',
            number: '+447123456789',
            email: 'sarah.johnson@democorp.com',
            relationship: 'Facilities Manager'
        },
        primaryJobTrade: 'HVAC',
        secondaryJobTrades: ['General'],
        tags: ['HVAC', 'Maintenance', 'Scheduled', 'Annual', 'Filters'],
        customAlerts: {
            acceptSLA: 120,
            onsiteSLA: 480,
            completedSLA: 720
        },
        project: 'Annual HVAC Maintenance',
        customerOrderNumber: 'PO-2024-004',
        referenceNumber: 'REF-004',
        jobOwner: 'Facilities Department',
        jobRef1: 'HVAC-002',
        jobRef2: 'ANNUAL-001',
        requiresApproval: false,
        preferredAppointmentDate: new Date('2024-01-17T08:00:00'),
        startDate: new Date('2024-01-16T08:00:00'),
        endDate: null,
        lockVisitDateTime: false,
        deployToMobile: true,
        isRecurringJob: true,
        completionTimeFromEngineerOnsite: false
    },
    {
        id: '5',
        jobNumber: 'JOB-2025-0907-005',
        ticketReference: 'SRTK104',
        customer: 'Tech Solutions Ltd',
        site: 'Manchester Office',
        description: 'Emergency pipe burst - Major water leak from a burst pipe in the basement',
        engineer: 'Sarah Johnson',
        status: 'allocated',
        priority: 'Critical',
        category: 'Plumbing',
        jobType: 'Emergency',
        targetCompletionTime: 360,
        dateLogged: new Date('2024-01-16T10:00:00'),
        dateAccepted: new Date('2024-01-16T10:05:00'),
        dateOnSite: new Date('2024-01-16T10:30:00'),
        dateCompleted: null,
        tenant: 'Guardian Environmental',
        alerts: [],
        reason: null,
        contact: {
            name: 'Mike Davis',
            number: '+447234567890',
            email: 'mike.davis@techsolutions.com',
            relationship: 'Office Manager'
        },
        reporter: {
            name: 'Mike Davis',
            number: '+447234567890',
            email: 'mike.davis@techsolutions.com',
            relationship: 'Office Manager'
        },
        primaryJobTrade: 'Plumbing',
        secondaryJobTrades: ['General'],
        tags: ['Plumbing', 'Emergency', 'Water Damage', 'Basement', 'Pipe Burst'],
        customAlerts: {
            acceptSLA: 15,
            onsiteSLA: 60,
            completedSLA: 360
        },
        project: 'Emergency Plumbing',
        customerOrderNumber: 'PO-2024-005',
        referenceNumber: 'REF-005',
        jobOwner: 'Office Management',
        jobRef1: 'PLUMB-002',
        jobRef2: 'EMERG-001',
        requiresApproval: false,
        preferredAppointmentDate: new Date('2024-01-16T10:00:00'),
        startDate: new Date('2024-01-16T10:00:00'),
        endDate: null,
        lockVisitDateTime: false,
        deployToMobile: true,
        isRecurringJob: false,
        completionTimeFromEngineerOnsite: false
    },
    {
        id: '6',
        jobNumber: 'JOB-2025-0907-006',
        customer: 'Demo Corporation',
        site: 'Manchester Office',
        description: 'Security system upgrade - Install new CCTV cameras and update access control system',
        engineer: 'Sophie Rodriguez',
        status: 'new',
        priority: 'Medium',
        category: 'Security Systems',
        jobType: 'Installation',
        targetCompletionTime: 720,
        dateLogged: new Date('2024-01-17T09:00:00'),
        dateAccepted: null,
        dateOnSite: null,
        dateCompleted: null,
        tenant: 'WorkFlowX',
        alerts: [],
        reason: null,
        contact: {
            name: 'David Chen',
            number: '+447456789012',
            email: 'david.chen@democorp.com',
            relationship: 'Security Manager'
        },
        reporter: {
            name: 'David Chen',
            number: '+447456789012',
            email: 'david.chen@democorp.com',
            relationship: 'Security Manager'
        },
        primaryJobTrade: 'Security Systems',
        secondaryJobTrades: ['Electrical', 'General'],
        tags: ['Security', 'Installation', 'CCTV', 'Access Control', 'Upgrade'],
        customAlerts: {
            acceptSLA: 120,
            onsiteSLA: 480,
            completedSLA: 1440
        },
        project: 'Security System Upgrade',
        customerOrderNumber: 'PO-2024-006',
        referenceNumber: 'REF-006',
        jobOwner: 'Security Department',
        jobRef1: 'SEC-001',
        jobRef2: 'UPGRADE-001',
        requiresApproval: true,
        preferredAppointmentDate: new Date('2024-01-18T08:00:00'),
        startDate: new Date('2024-01-17T09:00:00'),
        endDate: null,
        targetAttendanceDate: new Date('2024-01-18T09:00:00'),
        targetAttendanceTime: '09:00',
        allocatedVisitDate: new Date('2024-01-18T09:00:00'),
        allocatedVisitTime: '09:00',
        lockVisitDateTime: false,
        deployToMobile: true,
        isRecurringJob: false,
        completionTimeFromEngineerOnsite: false
    },
    {
        id: '7',
        jobNumber: 'JOB-2025-0907-007',
        customer: 'Tech Solutions Ltd',
        site: 'Manchester Office',
        description: 'Fire alarm system maintenance - Annual testing and inspection of fire detection system',
        engineer: 'Emma Wilson',
        status: 'allocated',
        priority: 'Medium',
        category: 'Fire Safety',
        jobType: 'Maintenance',
        targetCompletionTime: 360,
        dateLogged: new Date('2024-01-16T14:00:00'),
        dateAccepted: null,
        dateOnSite: null,
        dateCompleted: null,
        tenant: 'FM4U Ltd',
        alerts: [],
        reason: null,
        contact: {
            name: 'Mike Davis',
            number: '+447234567890',
            email: 'mike.davis@techsolutions.com',
            relationship: 'Office Manager'
        },
        reporter: {
            name: 'Mike Davis',
            number: '+447234567890',
            email: 'mike.davis@techsolutions.com',
            relationship: 'Office Manager'
        },
        primaryJobTrade: 'Fire Safety',
        secondaryJobTrades: ['Electrical', 'General'],
        tags: ['Fire Safety', 'Maintenance', 'Annual', 'Testing', 'Inspection'],
        customAlerts: {
            acceptSLA: 60,
            onsiteSLA: 240,
            completedSLA: 480
        },
        project: 'Annual Fire Safety Check',
        customerOrderNumber: 'PO-2024-007',
        referenceNumber: 'REF-007',
        jobOwner: 'Safety Department',
        jobRef1: 'FIRE-001',
        jobRef2: 'ANNUAL-002',
        requiresApproval: false,
        preferredAppointmentDate: new Date('2024-01-17T09:00:00'),
        startDate: new Date('2024-01-16T14:00:00'),
        endDate: null,
        targetAttendanceDate: new Date('2024-01-17T09:00:00'),
        targetAttendanceTime: '09:00',
        allocatedVisitDate: new Date('2024-01-17T09:00:00'),
        allocatedVisitTime: '09:00',
        lockVisitDateTime: false,
        deployToMobile: true,
        isRecurringJob: true,
        completionTimeFromEngineerOnsite: false
    },
    {
        id: '8',
        jobNumber: 'JOB-2025-0907-008',
        customer: 'Industrial Manufacturing',
        site: 'Birmingham Factory',
        description: 'Production line electrical fault - Intermittent power loss affecting production efficiency',
        engineer: 'Tom Brown',
        status: 'attended',
        priority: 'High',
        category: 'Electrical',
        jobType: 'Repair',
        targetCompletionTime: 300,
        dateLogged: new Date('2024-01-15T16:00:00'),
        dateAccepted: new Date('2024-01-15T16:15:00'),
        dateOnSite: null,
        dateCompleted: null,
        tenant: 'Guardian Environmental',
        alerts: [],
        reason: 'Awaiting parts delivery',
        contact: {
            name: 'Lisa Wilson',
            number: '+447345678901',
            email: 'lisa.wilson@indmanufacturing.com',
            relationship: 'Production Manager'
        },
        reporter: {
            name: 'Lisa Wilson',
            number: '+447345678901',
            email: 'lisa.wilson@indmanufacturing.com',
            relationship: 'Production Manager'
        },
        primaryJobTrade: 'Electrical',
        secondaryJobTrades: ['General'],
        tags: ['Electrical', 'Production', 'Power Loss', 'Repair', 'Critical'],
        customAlerts: {
            acceptSLA: 30,
            onsiteSLA: 120,
            completedSLA: 300
        },
        project: 'Production Line Maintenance',
        customerOrderNumber: 'PO-2024-008',
        referenceNumber: 'REF-008',
        jobOwner: 'Production Department',
        jobRef1: 'ELEC-002',
        jobRef2: 'PL-002',
        requiresApproval: false,
        preferredAppointmentDate: new Date('2024-01-16T08:00:00'),
        startDate: new Date('2024-01-15T16:00:00'),
        endDate: null,
        targetAttendanceDate: new Date('2024-01-16T08:00:00'),
        targetAttendanceTime: '08:00',
        allocatedVisitDate: new Date('2024-01-16T08:00:00'),
        allocatedVisitTime: '08:00',
        lockVisitDateTime: false,
        deployToMobile: true,
        isRecurringJob: false,
        completionTimeFromEngineerOnsite: false
    },
    {
        id: '9',
        jobNumber: 'JOB-2025-0907-009',
        customer: 'Demo Corporation',
        site: 'London HQ',
        description: 'Office painting and decoration - Refresh office spaces with new color scheme',
        engineer: 'David Chen',
        status: 'awaiting_parts',
        priority: 'Low',
        category: 'Painting',
        jobType: 'Maintenance',
        targetCompletionTime: 1440,
        dateLogged: new Date('2024-01-14T11:00:00'),
        dateAccepted: new Date('2024-01-14T11:30:00'),
        dateOnSite: new Date('2024-01-15T09:00:00'),
        dateCompleted: null,
        tenant: 'FM4U Ltd',
        alerts: [],
        reason: 'Paint supplies delayed',
        contact: {
            name: 'Sarah Johnson',
            number: '+447123456789',
            email: 'sarah.johnson@democorp.com',
            relationship: 'Facilities Manager'
        },
        reporter: {
            name: 'Sarah Johnson',
            number: '+447123456789',
            email: 'sarah.johnson@democorp.com',
            relationship: 'Facilities Manager'
        },
        primaryJobTrade: 'Painting',
        secondaryJobTrades: ['General'],
        tags: ['Painting', 'Decoration', 'Office', 'Refresh', 'Maintenance'],
        customAlerts: {
            acceptSLA: 120,
            onsiteSLA: 480,
            completedSLA: 1440
        },
        project: 'Office Refresh',
        customerOrderNumber: 'PO-2024-009',
        referenceNumber: 'REF-009',
        jobOwner: 'Facilities Department',
        jobRef1: 'PAINT-001',
        jobRef2: 'REFRESH-001',
        requiresApproval: false,
        preferredAppointmentDate: new Date('2024-01-15T09:00:00'),
        startDate: new Date('2024-01-14T11:00:00'),
        endDate: null,
        targetAttendanceDate: new Date('2024-01-15T09:00:00'),
        targetAttendanceTime: '09:00',
        allocatedVisitDate: new Date('2024-01-15T09:00:00'),
        allocatedVisitTime: '09:00',
        lockVisitDateTime: false,
        deployToMobile: true,
        isRecurringJob: false,
        completionTimeFromEngineerOnsite: false
    },
    {
        id: '10',
        jobNumber: 'JOB-2025-0907-010',
        customer: 'Tech Solutions Ltd',
        site: 'Manchester Office',
        description: 'Flooring replacement - Replace worn carpet tiles in meeting rooms and corridors',
        engineer: 'Emma Wilson',
        status: 'completed',
        priority: 'Medium',
        category: 'Flooring',
        jobType: 'Installation',
        targetCompletionTime: 600,
        dateLogged: new Date('2024-01-12T10:00:00'),
        dateAccepted: new Date('2024-01-12T10:15:00'),
        dateOnSite: new Date('2024-01-12T11:00:00'),
        dateCompleted: new Date('2024-01-12T17:00:00'),
        tenant: 'WorkFlowX',
        alerts: [],
        reason: null,
        contact: {
            name: 'Mike Davis',
            number: '+447234567890',
            email: 'mike.davis@techsolutions.com',
            relationship: 'Office Manager'
        },
        reporter: {
            name: 'Mike Davis',
            number: '+447234567890',
            email: 'mike.davis@techsolutions.com',
            relationship: 'Office Manager'
        },
        primaryJobTrade: 'Flooring',
        secondaryJobTrades: [],
        tags: ['Flooring', 'Repair', 'Corridor'],
        customAlerts: { acceptSLA: 60, onsiteSLA: 240, completedSLA: 480 },
        project: 'Flooring Refurb',
        customerOrderNumber: 'PO-2024-010',
        referenceNumber: 'REF-010',
        jobOwner: 'Facilities',
        jobRef1: 'FLR-001',
        jobRef2: 'REF-010',
        requiresApproval: false,
        preferredAppointmentDate: new Date('2024-01-12T09:00:00'),
        startDate: new Date('2024-01-12T09:00:00'),
        endDate: new Date('2024-01-12T17:00:00'),
        lockVisitDateTime: false,
        deployToMobile: true,
        isRecurringJob: false,
        completionTimeFromEngineerOnsite: true
    },
    {
        id: '11',
        jobNumber: 'JOB-2025-0907-011',
        customer: 'Retail Chain',
        site: 'London Store',
        description: 'Lighting failure in main sales floor - 20% of overhead lights not functioning',
        engineer: 'John Smith',
        status: 'allocated',
        priority: 'High',
        category: 'Electrical',
        jobType: 'Repair',
        targetCompletionTime: 240,
        dateLogged: new Date('2024-01-18T08:30:00'),
        dateAccepted: new Date('2024-01-18T09:00:00'),
        dateOnSite: null,
        dateCompleted: null,
        tenant: 'FM4U Ltd',
        alerts: [{ type: 'WARNING', message: 'Approaching On-site SLA' }],
        reason: null,
        contact: {
            name: 'Store Manager',
            number: '+44 20 7567 8901',
            email: 'store.mgr@retailchain.com',
            relationship: 'Store Manager'
        },
        reporter: {
            name: 'Store Manager',
            number: '+44 20 7567 8901',
            email: 'store.mgr@retailchain.com',
            relationship: 'Store Manager'
        },
        primaryJobTrade: 'Electrical',
        secondaryJobTrades: [],
        tags: ['Lighting', 'Sales Floor', 'Urgent'],
        customAlerts: { acceptSLA: 30, onsiteSLA: 120, completedSLA: 240 },
        project: 'Lighting Maintenance',
        customerOrderNumber: 'PO-2024-011',
        referenceNumber: 'REF-011',
        jobOwner: 'Regional Facilities',
        jobRef1: 'LGT-001',
        jobRef2: 'REF-011',
        requiresApproval: false,
        preferredAppointmentDate: new Date('2024-01-18T10:00:00'),
        startDate: new Date('2024-01-18T08:30:00'),
        endDate: null,
        lockVisitDateTime: false,
        deployToMobile: true,
        isRecurringJob: false,
        completionTimeFromEngineerOnsite: false
    },
    {
        id: '12',
        jobNumber: 'JOB-2025-0907-012',
        customer: 'Educational Institute',
        site: 'Manchester University',
        description: 'Boiler breakdown in Science Block - No heating or hot water',
        engineer: 'Mike Davis',
        status: 'parts_to_fit',
        priority: 'Critical',
        category: 'HVAC',
        jobType: 'Emergency',
        targetCompletionTime: 480,
        dateLogged: new Date('2024-01-18T07:15:00'),
        dateAccepted: new Date('2024-01-18T07:45:00'),
        dateOnSite: new Date('2024-01-18T08:30:00'),
        dateCompleted: null,
        tenant: 'Guardian Environmental',
        alerts: [{ type: 'OVERDUE', message: 'Completion SLA Breached' }],
        reason: 'Waiting for replacement pump',
        contact: {
            name: 'Estate Manager',
            number: '+44 20 7678 9012',
            email: 'estates@eduinst.com',
            relationship: 'Estate Manager'
        },
        reporter: {
            name: 'Estate Manager',
            number: '+44 20 7678 9012',
            email: 'estates@eduinst.com',
            relationship: 'Estate Manager'
        },
        primaryJobTrade: 'HVAC',
        secondaryJobTrades: ['Plumbing'],
        tags: ['Heating', 'Boiler', 'No Hot Water', 'Critical'],
        customAlerts: { acceptSLA: 30, onsiteSLA: 60, completedSLA: 480 },
        project: 'Emergency Heating',
        customerOrderNumber: 'PO-2024-012',
        referenceNumber: 'REF-012',
        jobOwner: 'Estates Dept',
        jobRef1: 'HEAT-001',
        jobRef2: 'REF-012',
        requiresApproval: true,
        preferredAppointmentDate: new Date('2024-01-18T08:00:00'),
        startDate: new Date('2024-01-18T07:15:00'),
        endDate: null,
        lockVisitDateTime: false,
        deployToMobile: true,
        isRecurringJob: false,
        completionTimeFromEngineerOnsite: false
    },
    {
        id: '13',
        jobNumber: 'JOB-2025-0907-013',
        customer: 'Financial Services',
        site: 'London HQ',
        description: 'Access control failure at main entrance - Turnstiles locked open',
        engineer: 'Sophie Rodriguez',
        status: 'attended',
        priority: 'High',
        category: 'Security Systems',
        jobType: 'Repair',
        targetCompletionTime: 120,
        dateLogged: new Date('2024-01-18T09:45:00'),
        dateAccepted: new Date('2024-01-18T10:00:00'),
        dateOnSite: null,
        dateCompleted: null,
        tenant: 'WorkFlowX',
        alerts: [],
        reason: null,
        contact: {
            name: 'Security Head',
            number: '+44 20 7789 0123',
            email: 'security@financialservices.com',
            relationship: 'Head of Security'
        },
        reporter: {
            name: 'Security Head',
            number: '+44 20 7789 0123',
            email: 'security@financialservices.com',
            relationship: 'Head of Security'
        },
        primaryJobTrade: 'Security Systems',
        secondaryJobTrades: ['Electrical'],
        tags: ['Access Control', 'Security', 'Entrance', 'High Priority'],
        customAlerts: { acceptSLA: 15, onsiteSLA: 60, completedSLA: 120 },
        project: 'Security Maintenance',
        customerOrderNumber: 'PO-2024-013',
        referenceNumber: 'REF-013',
        jobOwner: 'Security Dept',
        jobRef1: 'SEC-002',
        jobRef2: 'REF-013',
        requiresApproval: false,
        preferredAppointmentDate: new Date('2024-01-18T10:30:00'),
        startDate: new Date('2024-01-18T09:45:00'),
        endDate: null,
        lockVisitDateTime: false,
        deployToMobile: true,
        isRecurringJob: false,
        completionTimeFromEngineerOnsite: false
    },
    {
        id: '14',
        jobNumber: 'JOB-2025-0907-014',
        customer: 'Transport & Logistics',
        site: 'Southampton Terminal',
        description: 'Loading bay door jammed - Door 4 stuck in closed position',
        engineer: 'Unassigned',
        status: 'new',
        priority: 'Critical',
        category: 'General Maintenance',
        jobType: 'Emergency',
        targetCompletionTime: 240,
        dateLogged: new Date('2024-01-18T11:00:00'),
        dateAccepted: null,
        dateOnSite: null,
        dateCompleted: null,
        tenant: 'Guardian Environmental',
        alerts: [{ type: 'OVERDUE', message: 'Acceptance SLA Breached' }],
        reason: null,
        contact: {
            name: 'Terminal Manager',
            number: '+44 20 7890 1234',
            email: 'manager@transportlog.com',
            relationship: 'Terminal Manager'
        },
        reporter: {
            name: 'Terminal Manager',
            number: '+44 20 7890 1234',
            email: 'manager@transportlog.com',
            relationship: 'Terminal Manager'
        },
        primaryJobTrade: 'General',
        secondaryJobTrades: ['Electrical'],
        tags: ['Loading Bay', 'Door', 'Jammed', 'Critical Operations'],
        customAlerts: { acceptSLA: 15, onsiteSLA: 90, completedSLA: 240 },
        project: 'Terminal Maintenance',
        customerOrderNumber: 'PO-2024-014',
        referenceNumber: 'REF-014',
        jobOwner: 'Operations',
        jobRef1: 'DOOR-001',
        jobRef2: 'REF-014',
        requiresApproval: true,
        preferredAppointmentDate: new Date('2024-01-18T12:00:00'),
        startDate: new Date('2024-01-18T11:00:00'),
        endDate: null,
        lockVisitDateTime: false,
        deployToMobile: true,
        isRecurringJob: false,
        completionTimeFromEngineerOnsite: false
    },
    {
        id: 'JOB800',
        jobNumber: 'JOB800',
        ticketReference: 'SRTK231',
        customer: 'Edinburgh Royal NHS Trust',
        site: 'Castleview Children\'s Hospital',
        description: 'Light Out - Light fixture not working in Medical Gas Store',
        engineer: 'John Smith',
        status: 'new',
        priority: 'High',
        category: 'Electrical',
        jobType: 'Repair',
        targetCompletionTime: 240,
        dateLogged: new Date('2025-08-13T20:41:00'),
        dateAccepted: null,
        dateOnSite: null,
        dateCompleted: null,
        tenant: 'Healthcare',
        alerts: [],
        reason: null,
        contact: {
            name: 'Clive Owen',
            number: '+44 131 555 0123',
            email: 'clive.owen@hospital.nhs.uk',
            relationship: 'Facilities Manager'
        },
        reporter: {
            name: 'Clive Owen',
            number: '+44 131 555 0123',
            email: 'clive.owen@hospital.nhs.uk',
            relationship: 'Facilities Manager'
        },
        primaryJobTrade: 'Electrical',
        secondaryJobTrades: ['Lighting'],
        tags: ['Electrical', 'Lighting', 'NHS', 'Healthcare'],
        customAlerts: {
            acceptSLA: 30,
            onsiteSLA: 120,
            completedSLA: 240
        },
        project: 'NHS Maintenance',
        customerOrderNumber: 'NHS-2025-800',
        referenceNumber: 'REF-800',
        jobOwner: 'Facilities Department',
        jobRef1: 'ELEC-800',
        jobRef2: 'LIGHT-001',
        requiresApproval: false,
        preferredAppointmentDate: new Date('2025-08-14T09:00:00'),
        startDate: new Date('2025-08-13T20:41:00'),
        endDate: null,
        lockVisitDateTime: false,
        deployToMobile: true,
        isRecurringJob: false,
        completionTimeFromEngineerOnsite: false
    }
];
